# Generated by Django 5.1.1 on 2024-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement_apk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
