# Generated by Django 5.1.1 on 2024-09-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement_apk', '0007_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='employeemanagement_apk.employee'),
        ),
    ]
